openapi: 3.0.3
info:
  title: niimbluelib-headless server
  version: "1.0"

servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /connect:
    post:
      summary: Connect to the printer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - transport
                - address
              properties:
                transport:
                  type: string
                  enum:
                    - ble
                    - serial
                address:
                  type: string
            examples:
              Serial:
                value:
                  transport: "serial"
                  address: "COM8"
              BLE:
                value:
                  transport: "ble"
                  address: "26:03:03:c3:f9:11"
      responses:
        "200":
            description: Result
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/SimpleResponse"
        "500":
            description: Connection failure
  /disconnect:
    post:
      summary: Disconnect from the printer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
            description: Result
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/SimpleResponse"
        "500":
            description: Connection failure

  /connected:
    get:
      summary: Check the printer connection status
      responses:
        "200":
          description: Connection status
          content:
            application/json:
              schema:
                type: object
                properties:
                  connected:
                    type: boolean
  /info:
    get:
      summary: Check the printer info
      responses:
        "200":
          description: Connection status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrinterInfo'



  /print:
    post:
      summary: Print image
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PrintOptions"
      responses:
        "200":
            description: Success
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/SimpleResponse"

  /scan:
    post:
      summary: Scan for devices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - transport
              properties:
                transport:
                  type: string
                  enum:
                    - ble
                    - serial
      responses:
        "200":
          description: Device list
          content:
            application/json:
              schema:
                type: object
                properties:
                  devices:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        address:
                          type: string
                      required:
                        - name
                        - address
                additionalProperties: false
                required:
                  - devices


components:
  schemas:
    SimpleResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string

    PrintOptions:
      type: object
      properties:
        printDirection:
          type: string
          enum: ["left", "top"]
          default: left

        printTask:
          type: string
          example: B1

        quantity:
          type: number
          minimum: 1
          default: 1

        labelType:
          type: number
          minimum: 1
          default: 1

        density:
          type: number
          minimum: 1
          default: 3

        imageBase64:
          type: string
          format: byte
          default: null
          description: imageUrl or imageBase64 must be defined

        imageUrl:
          type: string
          format: uri
          default: null
          example: https://i.imgur.com/TzzVlc4.png
          description: imageUrl or imageBase64 must be defined

        labelWidth:
          type: number
          minimum: 8
          default: null

        labelHeight:
          type: number
          minimum: 8
          default: null

        threshold:
          type: number
          minimum: 1
          maximum: 255
          default: 128

        imagePosition:
          type: string
          enum: ["centre", "top", "right top", "right", "right bottom", "bottom", "left bottom", "left", "left top"]
          default: centre
          description: See [sharp resize options.position](https://sharp.pixelplumbing.com/api-resize)

        imageFit:
          type: string
          enum: ["contain", "cover", "fill", "inside", "outside"]
          default: contain
          description: See [sharp resize options.fit](https://sharp.pixelplumbing.com/api-resize)

    PrinterInfo:
      type: object
      properties:
        printerInfo:
          type: object
          properties:
            connectResult:
              type: integer
            protocolVersion:
              type: integer
            modelId:
              type: integer
            serial:
              type: string
            mac:
              type: string
            charge:
              type: integer
            autoShutdownTime:
              type: integer
            labelType:
              type: integer
            hardwareVersion:
              type: string
            softwareVersion:
              type: string
          additionalProperties: false
        modelMetadata:
          type: object
          properties:
            model:
              type: string
            id:
              type: array
              items:
                type: integer
            dpi:
              type: integer
            printDirection:
              type: string
            printheadPixels:
              type: integer
            paperTypes:
              type: array
              items:
                type: integer
            densityMin:
              type: integer
            densityMax:
              type: integer
            densityDefault:
              type: integer
          additionalProperties: false
        detectedPrintTask:
          type: string
      additionalProperties: false
      required:
        - printerInfo
        - modelMetadata
        - detectedPrintTask